# Generated by Django 3.2.7 on 2021-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='readersnook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('uphno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='register1',
            fields=[
            ('uid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('uphno', models.IntegerField()),
                ('umail', models.CharField(max_length=255)),
                ('upass', models.CharField(max_length=255)),
                ('cpass', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
