# Generated by Django 3.2.7 on 2021-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='uphno',
            field=models.CharField(max_length=255),
        ),
    ]
