# Generated by Django 3.2.7 on 2021-10-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0002_alter_register1_uphno'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('fid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umail', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
