# Generated by Django 2.0 on 2021-10-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0003_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Book',
            fields=[
                ('bid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('umail', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('bname', models.CharField(max_length=255)),
                ('bprice', models.CharField(max_length=255)),
                ('bimage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sell',
            },
        ),
        migrations.AlterField(
            model_name='readersnook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
