# Generated by Django 2.0 on 2021-10-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0004_auto_20211007_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_book',
            old_name='bid',
            new_name='b_id',
        ),
    ]
