# Generated by Django 2.0 on 2021-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0005_auto_20211007_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_book',
            name='bimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
