# Generated by Django 2.0 on 2021-10-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0007_auto_20211007_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('r_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=255)),
                ('r_name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'communication',
            },
        ),
    ]
