# Generated by Django 2.0 on 2021-10-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0011_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
    ]
