# Generated by Django 2.0 on 2021-10-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0012_remove_post_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='BookSearch',
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
        migrations.DeleteModel(
            name='feed',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Misc',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='readersnook',
        ),
        migrations.DeleteModel(
            name='register1',
        ),
        migrations.DeleteModel(
            name='Upload_Book',
        ),
        migrations.DeleteModel(
            name='w_Item',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
