# Generated by Django 2.0 on 2021-10-18 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readersnook', '0013_auto_20211018_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('author', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('pdf', models.FileField(upload_to='pdf')),
                ('recommended_books', models.BooleanField(default=False)),
                ('fiction_books', models.BooleanField(default=False)),
                ('business_books', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categories')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('r_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=255)),
                ('r_name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'communication',
            },
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('fid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umail', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=50)),
                ('genre', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=200, null=True)),
                ('day', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=50)),
                ('genre', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'misc',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='readersnook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('uphno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='register1',
            fields=[
                ('uid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('uphno', models.CharField(max_length=255)),
                ('umail', models.CharField(max_length=255)),
                ('upass', models.CharField(max_length=255)),
                ('cpass', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Upload_Book',
            fields=[
                ('b_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('umail', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('bname', models.CharField(max_length=255)),
                ('bprice', models.CharField(max_length=255)),
                ('bimage', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
            options={
                'db_table': 'sell',
            },
        ),
        migrations.CreateModel(
            name='w_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=50)),
                ('genre', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'w_item',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='readersnook.Category'),
        ),
    ]
