# Generated by Django 2.0 on 2021-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readersnook', '0014_auto_20211018_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uname',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
